title: Boran Takak
author: Boran Takak
subtitle: blog

remote_theme: ankitsultana/researcher@gem


url: "izuta-k.github.io"
baseurl: "/izuta-k"

footer_only_homepage: true
footer_url: "https://github.com/izuta-k"
footer_text: "weeping angel"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Social"
   absolute-link: "www.x.com/izumivondegure"
